### ISSUE TITLE
Does not correctly process synthesis entries

### ISSUE THREAD

**Issue by RWeb** [msarilar/EDEngineer#22]
The program does not correctly process synthesis entries, resulting in incorrect counts. For example, I tried doing a basic SRV repair.

I started with the following count in game and ED - Engineer
- Iron: 42
- Nickel: 44

"SRV Repair - Basic" requires
- Iron x2
- Nickel x1

After performing the repair, the following line was added to log:
`{ "timestamp":"2016-11-07T02:19:36Z", "event":"Synthesis", "Name":"Repair Basic", "Materials":{ "iron":2, "nickel":1 } }
`

The count in game was updated to:
- Iron: 40
- Nickel: 43

While the count in "ED - Engineer" was updated to:
- Iron: 44
- Nickel: 44

**Comment by msarilar** [comment]
thanks for the report! it's fixed in 1.0.0.15

**Comment by RWeb** [comment]
I'm still seeing an issue with this. Same conditions as above, except that while the iron entry is updated correctly, the nickel entry does not change.

**Comment by msarilar** [comment]
thanks for the report, will be fixed in next version 1.0.0.19! (and this time, for good)
