### ISSUE TITLE
Configure Graphics

### ISSUE THREAD

**Issue by Orsum-VR** [msarilar/EDEngineer#483]
When selecting right panel font size and moving it to the left makes ED Engineer crash everytime

**Comment by msarilar** [comment]
fixed in b28cf4be6b711a58a7e431d5a6d31d23853b31a3

**Comment by jwalt** [comment]
It seems this has not been fixed entirely -- In 1.1.5.3 it still crashes, but only if you have a shopping list with some specific entries, and with various right panel font ratios.

For example, for me it reproducibly crashes when adding G2 increased FSD range at right panel font ratio 60. It doesn't crash when adding G1,3,4,5. G2 also does not crash with font ratio 70. But 70 is not safe either: in a larger shopping list, it happened with 70 as well, but I didn't investigate any further. 

Right panel font ratio 80 worked fine for everything I did so far.

Maybe that's what bug #417 is about.

**Comment by msarilar** [comment]
very weird ; thanks a lot for bringing this up especially with the failing value @jwalt 

I had a quick look and couldn't figure it out and I unfortunately don't have much time to dive back into WPF inner mechanisms but I hotfixed the app with an ugly hack - could you confirm this doesn't crash anymore for you?

**Comment by jwalt** [comment]
I have no way to build the application, but I will give feedback when I get around to installing a future update.
